-- 删除表
if exists(select * from sysobjects where id = object_id(N'[TmScheduleEmployee]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table TmScheduleEmployee

GO
CREATE TABLE [TmScheduleEmployee](
[Id]  INT NOT NULL IDENTITY(1,1),
[Fid]  VARCHAR(20),
[ScheduleUid]  VARCHAR(22),
[EmpUid]  VARCHAR(22),
[DeptUid]  VARCHAR(22),
[ScheduleYear]  VARCHAR(10),
[OrgUid]  VARCHAR(20),
[GroupUid]  VARCHAR(20),
[EnableDate]  VARCHAR(19),
[DisableDate]  VARCHAR(19),
[Dr]  INT,
[Ts]  BIGINT,
[CreateBy]  VARCHAR(20),
[CreateName]  VARCHAR(100),
[CreateDate]  VARCHAR(19),
[UpdateBy]  VARCHAR(20),
[UpdateName]  VARCHAR(100),
[UpdateDate]  VARCHAR(19),
PRIMARY KEY (Id));
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'排班人员' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmScheduleEmployee';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'主键', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmScheduleEmployee', @level2type=N'COLUMN',@level2name=N'Id';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'唯一标识', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmScheduleEmployee', @level2type=N'COLUMN',@level2name=N'Fid';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'排班UID', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmScheduleEmployee', @level2type=N'COLUMN',@level2name=N'ScheduleUid';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'员工', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmScheduleEmployee', @level2type=N'COLUMN',@level2name=N'EmpUid';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'部门', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmScheduleEmployee', @level2type=N'COLUMN',@level2name=N'DeptUid';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'年度', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmScheduleEmployee', @level2type=N'COLUMN',@level2name=N'ScheduleYear';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'组织', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmScheduleEmployee', @level2type=N'COLUMN',@level2name=N'OrgUid';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'集团', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmScheduleEmployee', @level2type=N'COLUMN',@level2name=N'GroupUid';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'有效开始时间', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmScheduleEmployee', @level2type=N'COLUMN',@level2name=N'EnableDate';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'有效截止时间', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmScheduleEmployee', @level2type=N'COLUMN',@level2name=N'DisableDate';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'删除标记', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmScheduleEmployee', @level2type=N'COLUMN',@level2name=N'Dr';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'时间戳', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmScheduleEmployee', @level2type=N'COLUMN',@level2name=N'Ts';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'创建人', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmScheduleEmployee', @level2type=N'COLUMN',@level2name=N'CreateBy';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'创建人名称', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmScheduleEmployee', @level2type=N'COLUMN',@level2name=N'CreateName';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'创建时间', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmScheduleEmployee', @level2type=N'COLUMN',@level2name=N'CreateDate';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'更新人', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmScheduleEmployee', @level2type=N'COLUMN',@level2name=N'UpdateBy';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'更新人名称', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmScheduleEmployee', @level2type=N'COLUMN',@level2name=N'UpdateName';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'更新时间', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmScheduleEmployee', @level2type=N'COLUMN',@level2name=N'UpdateDate';


GO

--FapTable元数据
delete from FapTable where TableName='TmScheduleEmployee'
INSERT INTO [FapTable]([IsTree],[IsPagination],[IsSync],[Dr],[TraceAble],[Ts],[Fid],[TableName],[TableComment],[TableType],[TableCategory],[TableMode],[ProductUid],[DataInterceptor],[ScriptInjection],[SqlInjection],[TableFeature],[TableDesc],[CreateDate],[UpdateBy],[UpdateName],[UpdateDate],[GroupUid],[OrgUid],[SubTable],[MainTable],[EnableDate],[DisableDate],[CreateBy],[CreateName]) VALUES(0,1,1,0,0,637200746679654973,'689457915819458560','TmScheduleEmployee','排班人员','BUSINESS','Tm','SINGLE','HCM','',NULL,NULL,'','','2020-03-17 20:44:27',NULL,NULL,NULL,'','',NULL,'','2020-03-17 20:44:26','9999-12-31 23:59:59','3521928112763830273','wangyanfei');
GO
--FapColumn元数据
delete from FapColumn where TableName='TmScheduleEmployee'
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,10,0,0,0,0,0,0,0,1,0,0,0,0,0,637200746683558995,'689458586757103616','TmScheduleEmployee','Id','主键','INT','PK','',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'wangyanfei',NULL,'2020-03-17 20:44:28',NULL,NULL,NULL,'2020-03-17 20:44:27','9999-12-31 23:59:59',NULL,NULL,'3521928112763830273',NULL,'0',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,20,0,0,0,0,0,0,0,1,0,0,0,1,0,637200746684433347,'689458587486912512','TmScheduleEmployee','Fid','唯一标识','TEXT','UID','',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'wangyanfei',NULL,'2020-03-17 20:44:28',NULL,NULL,NULL,'2020-03-17 20:44:27','9999-12-31 23:59:59',NULL,NULL,'3521928112763830273',NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,10,0,1,0,0,0,0,0,1,0,0,0,980,0,637200746684841848,'689458587830845440','TmScheduleEmployee','OrgUid','组织','TEXT','UID','',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'wangyanfei',NULL,'2020-03-17 20:44:28',NULL,NULL,NULL,'2020-03-17 20:44:27','9999-12-31 23:59:59',NULL,NULL,'3521928112763830273',NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,10,0,1,0,0,0,0,0,1,0,0,0,981,0,637200746685244144,'689458588170584064','TmScheduleEmployee','GroupUid','集团','TEXT','UID','',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'wangyanfei',NULL,'2020-03-17 20:44:28',NULL,NULL,NULL,'2020-03-17 20:44:27','9999-12-31 23:59:59',NULL,NULL,'3521928112763830273',NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,19,0,0,0,0,0,0,0,1,0,0,0,982,0,637200746685756782,'689458588598403072','TmScheduleEmployee','EnableDate','有效开始时间','DATETIME','DATETIME','',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'wangyanfei',NULL,'2020-03-17 20:44:28',NULL,NULL,NULL,'2020-03-17 20:44:27','9999-12-31 23:59:59',NULL,NULL,'3521928112763830273',NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,19,0,0,0,0,0,0,0,1,0,0,0,983,0,637200746686151923,'689458588929753088','TmScheduleEmployee','DisableDate','有效截止时间','DATETIME','DATETIME','',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'wangyanfei',NULL,'2020-03-17 20:44:28',NULL,NULL,NULL,'2020-03-17 20:44:27','9999-12-31 23:59:59',NULL,NULL,'3521928112763830273',NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(10,0,10,0,0,0,0,0,0,0,1,0,0,0,984,0,637200746686650223,'689458589349183488','TmScheduleEmployee','Dr','删除标记','CHECKBOX','BOOL','',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'wangyanfei',NULL,'2020-03-17 20:44:28',NULL,NULL,NULL,'2020-03-17 20:44:27','9999-12-31 23:59:59',NULL,NULL,'3521928112763830273',NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,10,0,0,0,0,0,0,0,1,0,0,0,985,0,637200746687059418,'689458589693116416','TmScheduleEmployee','Ts','时间戳','TEXT','LONG','',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'wangyanfei',NULL,'2020-03-17 20:44:28',NULL,NULL,NULL,'2020-03-17 20:44:27','9999-12-31 23:59:59',NULL,NULL,'3521928112763830273',NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,10,0,1,0,0,0,0,0,1,0,0,0,986,0,637200746687559957,'689458590112546816','TmScheduleEmployee','CreateBy','创建人','TEXT','STRING','',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'wangyanfei',NULL,'2020-03-17 20:44:28',NULL,NULL,NULL,'2020-03-17 20:44:27','9999-12-31 23:59:59',NULL,NULL,'3521928112763830273',NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(100,0,10,0,1,0,0,0,0,0,1,0,0,0,987,0,637200746687988437,'689458590469062656','TmScheduleEmployee','CreateName','创建人名称','TEXT','STRING','',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'wangyanfei',NULL,'2020-03-17 20:44:28',NULL,NULL,NULL,'2020-03-17 20:44:27','9999-12-31 23:59:59',NULL,NULL,'3521928112763830273',NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,10,0,1,0,0,0,0,0,1,0,0,0,988,0,637200746688440298,'689458590850744320','TmScheduleEmployee','CreateDate','创建时间','DATETIME','DATETIME','',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'wangyanfei',NULL,'2020-03-17 20:44:28',NULL,NULL,NULL,'2020-03-17 20:44:27','9999-12-31 23:59:59',NULL,NULL,'3521928112763830273',NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,10,0,1,0,0,0,0,0,1,0,0,0,989,0,637200746688895371,'689458591232425984','TmScheduleEmployee','UpdateBy','更新人','TEXT','STRING','',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'wangyanfei',NULL,'2020-03-17 20:44:28',NULL,NULL,NULL,'2020-03-17 20:44:27','9999-12-31 23:59:59',NULL,NULL,'3521928112763830273',NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(100,0,10,0,1,0,0,0,0,0,1,0,0,0,990,0,637200746689283575,'689458591555387392','TmScheduleEmployee','UpdateName','更新人名称','TEXT','STRING','',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'wangyanfei',NULL,'2020-03-17 20:44:28',NULL,NULL,NULL,'2020-03-17 20:44:27','9999-12-31 23:59:59',NULL,NULL,'3521928112763830273',NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,10,0,1,0,0,0,0,0,1,0,0,0,991,0,637200746689669251,'689458591882543104','TmScheduleEmployee','UpdateDate','更新时间','DATETIME','DATETIME','',NULL,NULL,NULL,NULL,NULL,NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'wangyanfei',NULL,'2020-03-17 20:44:28',NULL,NULL,NULL,'2020-03-17 20:44:27','9999-12-31 23:59:59',NULL,NULL,'3521928112763830273',NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(22,0,120,1,1,0,0,0,0,0,0,0,0,0,3,0,689469542526615552,'689458823303266304','TmScheduleEmployee','ScheduleUid','排班UID','TEXT','STRING','',NULL,'','',NULL,'','','','3521928112763830273','','wangyanfei','','2020-03-17 21:06:14','','','wangyanfei','','2020-03-17 20:47:12','','',NULL,'2020-03-17 20:47:11','9999-12-31 23:59:59','','','3521928112763830273','','3','','',NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(22,0,120,1,1,0,0,0,0,0,0,1,0,0,4,0,637200748848134018,'689459968549584896','TmScheduleEmployee','EmpUid','员工','REFERENCE','STRING','',NULL,'','',NULL,'','','',NULL,'',NULL,'',NULL,'','Fid','wangyanfei','','2020-03-17 20:48:04','EmpName','',NULL,'2020-03-17 20:48:03','9999-12-31 23:59:59','GridReference','Employee','3521928112763830273','','3','','',NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(22,0,120,1,1,0,0,0,0,0,0,1,0,0,5,0,637200749491680523,'689460405847719936','TmScheduleEmployee','DeptUid','部门','REFERENCE','STRING','',NULL,'','',NULL,'','','',NULL,'',NULL,'',NULL,'','Fid','wangyanfei','','2020-03-17 20:49:09','DeptName','',NULL,'2020-03-17 20:49:08','9999-12-31 23:59:59','TreeReference','OrgDept','3521928112763830273','','3','','',NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(10,0,120,1,1,0,0,0,0,0,0,1,0,0,7,0,637200750374418894,'689460945486872576','TmScheduleEmployee','ScheduleYear','年度','TEXT','STRING','',NULL,'','',NULL,'','','',NULL,'',NULL,'',NULL,'','','wangyanfei','','2020-03-17 20:50:37','','',NULL,'2020-03-17 20:50:36','9999-12-31 23:59:59','','','3521928112763830273','','3','','',NULL,NULL);
GO


-- 删除表
if exists(select * from sysobjects where id = object_id(N'[TmSchedule]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table TmSchedule

GO
CREATE TABLE [TmSchedule](
[Id]  INT NOT NULL IDENTITY(1,1),
[Fid]  VARCHAR(20),
[ScheduleUid]  VARCHAR(22),
[ShiftUid]  VARCHAR(20),
[WorkDay]  VARCHAR(20),
[StartTime]  VARCHAR(19),
[EndTime]  VARCHAR(19),
[LateTime]  VARCHAR(19),
[LeaveTime]  VARCHAR(19),
[StartCardTime]  VARCHAR(19),
[EndCardTime]  VARCHAR(19),
[WorkHoursLength]  DECIMAL(20,1),
[RestMinutesLength]  DECIMAL(20,1),
[RestStartTime]  VARCHAR(19),
[RestEndTime]  VARCHAR(19),
[OrgUid]  VARCHAR(20),
[GroupUid]  VARCHAR(20),
[EnableDate]  VARCHAR(19),
[DisableDate]  VARCHAR(19),
[Dr]  INT,
[Ts]  BIGINT,
[CreateBy]  VARCHAR(20),
[CreateName]  VARCHAR(100),
[CreateDate]  VARCHAR(19),
[UpdateBy]  VARCHAR(20),
[UpdateName]  VARCHAR(100),
[UpdateDate]  VARCHAR(19),
PRIMARY KEY (Id));
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'排班表' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule';
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'主键', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'Id';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'唯一标识', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'Fid';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'排班UID', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'ScheduleUid';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'班次', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'ShiftUid';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'工作日期', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'WorkDay';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'上班时间', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'StartTime';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'下班时间', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'EndTime';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'迟到时间', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'LateTime';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'早退时间', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'LeaveTime';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'计算打卡开始时间', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'StartCardTime';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'计算打卡结束时间', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'EndCardTime';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'排班工作时长', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'WorkHoursLength';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'排班休息时长', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'RestMinutesLength';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'休息开始时间', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'RestStartTime';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'休息结束时间', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'RestEndTime';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'组织', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'OrgUid';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'集团', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'GroupUid';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'有效开始时间', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'EnableDate';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'有效截止时间', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'DisableDate';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'删除标记', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'Dr';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'时间戳', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'Ts';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'创建人', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'CreateBy';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'创建人名称', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'CreateName';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'创建时间', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'CreateDate';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'更新人', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'UpdateBy';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'更新人名称', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'UpdateName';

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'更新时间', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TmSchedule', @level2type=N'COLUMN',@level2name=N'UpdateDate';


GO

--FapTable元数据
delete from FapTable where TableName='TmSchedule'
INSERT INTO [FapTable]([IsTree],[IsPagination],[IsSync],[Dr],[TraceAble],[Ts],[Fid],[TableName],[TableComment],[TableType],[TableCategory],[TableMode],[ProductUid],[DataInterceptor],[ScriptInjection],[SqlInjection],[TableFeature],[TableDesc],[CreateDate],[UpdateBy],[UpdateName],[UpdateDate],[GroupUid],[OrgUid],[SubTable],[MainTable],[EnableDate],[DisableDate],[CreateBy],[CreateName]) VALUES(0,0,1,0,0,635992123465793337,'1d1011e6828e842fe8b9','TmSchedule','排班表','BUSINESS','Tm','SINGLE','HCM','',NULL,NULL,'InsCaseFeature:保险类特性','员工一年的排班明细数据','2016-05-18 23:52:26',NULL,NULL,'2016-05-18 23:52:26',NULL,NULL,NULL,'','2016-05-18 23:52:26','9999-12-31 23:59:59',NULL,NULL);
GO
--FapColumn元数据
delete from FapColumn where TableName='TmSchedule'
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,10,0,1,0,NULL,NULL,0,0,1,0,0,0,986,0,636356455532695632,'1d1011e6828e842fe8c5','TmSchedule','CreateBy','创建人','TEXT','STRING',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2016-05-18 23:52:26',NULL,NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,10,0,1,0,NULL,NULL,0,0,1,0,0,0,988,0,636356455532695632,'1d1011e6828e842fe8c7','TmSchedule','CreateDate','创建时间','DATETIME','DATETIME',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2016-05-18 23:52:26',NULL,NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(100,0,10,0,1,0,NULL,NULL,0,0,1,0,0,0,987,0,636356455532695632,'1d1011e6828e842fe8c6','TmSchedule','CreateName','创建人名称','TEXT','STRING',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2016-05-18 23:52:26',NULL,NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,19,0,0,0,NULL,NULL,0,0,1,0,0,0,983,0,636356455532695632,'1d1011e6828e842fe8c2','TmSchedule','DisableDate','有效截止时间','DATETIME','DATETIME',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2016-05-18 23:52:26',NULL,NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(10,0,10,0,0,0,NULL,NULL,0,0,1,0,0,0,984,0,636356455532695632,'1d1011e6828e842fe8c3','TmSchedule','Dr','删除标记','CHECKBOX','BOOL',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2016-05-18 23:52:26',NULL,NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(22,0,80,1,1,0,0,0,0,0,0,1,0,0,2,0,689465694667931648,'1d1011e6828e842fe8bc','TmSchedule','ScheduleUid','排班UID','TEXT','STRING',NULL,NULL,'','',NULL,'','',NULL,'3521928112763830273','','wangyanfei','','2020-03-17 20:58:34','','',NULL,'','2017-07-14 16:12:33','','',NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59','','',NULL,'','1','','',NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,19,0,0,0,NULL,NULL,0,0,1,0,0,0,982,0,636356455532695632,'1d1011e6828e842fe8c1','TmSchedule','EnableDate','有效开始时间','DATETIME','DATETIME',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2016-05-18 23:52:26',NULL,NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,100,1,1,0,NULL,NULL,10,10240,0,1,0,0,10,0,636356455532695632,'78cb11e688795f91a10c','TmSchedule','EndCardTime','计算打卡结束时间','DATETIME','DATETIME',NULL,NULL,NULL,NULL,NULL,'','',NULL,NULL,NULL,NULL,'','2016-09-12 17:29:16','',NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,100,1,1,0,NULL,NULL,10,10240,0,1,0,0,6,0,636356455532695632,'77cc11e68b1a1cad8702','TmSchedule','EndTime','下班时间','DATETIME','DATETIME',NULL,NULL,NULL,NULL,NULL,'','',NULL,NULL,NULL,NULL,'','2016-09-11 11:02:02','',NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,20,0,0,0,NULL,NULL,0,0,1,0,0,0,1,0,636356455532695632,'1d1011e6828e842fe8bb','TmSchedule','Fid','唯一标识','TEXT','UID',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2016-05-18 23:52:26',NULL,NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,'${FAP::UUID}','1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,10,0,1,0,NULL,NULL,0,0,1,0,0,0,981,0,636356455532695632,'1d1011e6828e842fe8c0','TmSchedule','GroupUid','集团','TEXT','UID',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2016-05-18 23:52:26',NULL,NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,'${FAP::UUID}','1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,10,0,0,0,NULL,NULL,0,0,1,0,0,0,0,0,636356455532695632,'1d1011e6828e842fe8ba','TmSchedule','Id','主键','INT','PK',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2016-05-18 23:52:26',NULL,NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,100,1,1,0,NULL,NULL,10,10240,0,1,0,0,7,0,636356455532695632,'77cc11e68b1a1cad8703','TmSchedule','LateTime','迟到时间','DATETIME','DATETIME',NULL,NULL,NULL,NULL,NULL,'','',NULL,NULL,NULL,NULL,'','2016-09-11 11:02:02','',NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,100,1,1,0,NULL,NULL,10,10240,0,1,0,0,8,0,636356455532695632,'77cc11e68b1a1cad8704','TmSchedule','LeaveTime','早退时间','DATETIME','DATETIME',NULL,NULL,NULL,NULL,NULL,'','',NULL,NULL,NULL,NULL,'','2016-09-11 11:02:02','',NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,10,0,1,0,NULL,NULL,0,0,1,0,0,0,980,0,636356455532695632,'1d1011e6828e842fe8bf','TmSchedule','OrgUid','组织','TEXT','UID',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2016-05-18 23:52:26',NULL,NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,'${FAP::UUID}','1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,100,1,1,0,NULL,NULL,10,10240,0,1,0,0,14,0,636356455532695632,'679611e78cc237941138','TmSchedule','RestEndTime','休息结束时间','DATETIME','DATETIME',NULL,NULL,NULL,NULL,NULL,'','',NULL,NULL,NULL,NULL,'','2017-07-13 14:40:54','',NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,100,1,1,0,NULL,NULL,10,10240,0,1,0,0,13,0,636356455532695632,'797711e68879442f506c','TmSchedule','RestMinutesLength','排班休息时长','DOUBLE','DOUBLE',NULL,NULL,NULL,NULL,NULL,'','',NULL,NULL,NULL,NULL,'','2016-09-13 13:59:44','',NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,'0.0','1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,100,1,1,0,NULL,NULL,10,10240,0,1,0,0,13,0,636356455532695632,'679611e78cc237941137','TmSchedule','RestStartTime','休息开始时间','DATETIME','DATETIME',NULL,NULL,NULL,NULL,NULL,'','',NULL,NULL,NULL,NULL,'','2017-07-13 14:40:54','',NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,80,1,1,0,NULL,NULL,10,10240,0,1,0,0,3,0,636356455532695632,'1d1011e6828e842fe8bd','TmSchedule','ShiftUid','班次','REFERENCE','STRING',NULL,NULL,NULL,NULL,NULL,'','',NULL,NULL,NULL,NULL,'','2016-05-18 23:52:26','','Fid',NULL,NULL,'2017-07-14 16:12:33','ShiftName',NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59','GridReference','TmShift',NULL,NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,100,1,1,0,NULL,NULL,10,10240,0,1,0,0,9,0,636356455532695632,'78cb11e688795f91a10b','TmSchedule','StartCardTime','计算打卡开始时间','DATETIME','DATETIME',NULL,NULL,NULL,NULL,NULL,'','',NULL,NULL,NULL,NULL,'','2016-09-12 17:29:16','',NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,100,1,1,0,NULL,NULL,10,10240,0,1,0,0,5,0,636356455532695632,'77cc11e68b1a1cad8701','TmSchedule','StartTime','上班时间','DATETIME','DATETIME',NULL,NULL,NULL,NULL,NULL,'','',NULL,NULL,NULL,NULL,'','2016-09-11 11:02:02','',NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,10,0,0,0,NULL,NULL,0,0,1,0,0,0,985,0,636356455532695632,'1d1011e6828e842fe8c4','TmSchedule','Ts','时间戳','TEXT','LONG',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2016-05-18 23:52:26',NULL,NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,10,0,1,0,NULL,NULL,0,0,1,0,0,0,989,0,636356455532695632,'1d1011e6828e842fe8c8','TmSchedule','UpdateBy','更新人','TEXT','STRING',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2016-05-18 23:52:26',NULL,NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,10,0,1,0,NULL,NULL,0,0,1,0,0,0,991,0,636356455532695632,'1d1011e6828e842fe8ca','TmSchedule','UpdateDate','更新时间','DATETIME','DATETIME',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2016-05-18 23:52:26',NULL,NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(100,0,10,0,1,0,NULL,NULL,0,0,1,0,0,0,990,0,636356455532695632,'1d1011e6828e842fe8c9','TmSchedule','UpdateName','更新人名称','TEXT','STRING',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2016-05-18 23:52:26',NULL,NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,100,1,1,0,NULL,NULL,10,10240,0,1,0,0,4,0,636356455532695632,'1d1011e6828e842fe8be','TmSchedule','WorkDay','工作日期','DATE','STRING',NULL,NULL,NULL,NULL,NULL,'','',NULL,NULL,NULL,NULL,'','2016-05-18 23:52:26','',NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,NULL,'1',NULL,NULL,NULL,NULL);
GO
INSERT INTO [FapColumn]([ColLength],[ColPrecision],[DisplayWidth],[EditAble],[NullAble],[Dr],[MinValue],[MaxValue],[FileCount],[FileSize],[IsDefaultCol],[ShowAble],[MultiAble],[IsMultiLang],[ColOrder],[IsObsolete],[Ts],[Fid],[TableName],[ColName],[ColComment],[CtrlType],[ColType],[GroupUid],[DefaultValueClass],[ComboxSource],[FileSuffix],[ComponentUid],[RemoteChkURL],[RemoteChkMsg],[OrgUid],[UpdateBy],[RefCols],[UpdateName],[RefReturnMapping],[UpdateDate],[ColGroup],[RefID],[CreateName],[RefCode],[CreateDate],[RefName],[RefCondition],[CalculationExpr],[EnableDate],[DisableDate],[RefType],[RefTable],[CreateBy],[ColDefault],[ColProperty],[SortDirection],[DisplayFormat],[MainTable],[MainTableCol]) VALUES(20,0,100,1,1,0,NULL,NULL,10,10240,0,1,0,0,11,0,636356455532695632,'797711e68879442f506b','TmSchedule','WorkHoursLength','排班工作时长','DOUBLE','DOUBLE',NULL,NULL,NULL,NULL,NULL,'','',NULL,NULL,NULL,NULL,'','2016-09-13 13:59:44','',NULL,NULL,NULL,'2017-07-14 16:12:33',NULL,NULL,NULL,'2017-07-14 16:12:33','9999-12-31 23:59:59',NULL,NULL,NULL,'0.0','1',NULL,NULL,NULL,NULL);
GO


